services:

  mysql:
    image: mysql
    container_name: mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    env_file:
      - ./db/db.env
    volumes:
      - ./db/tools:/tools
      - ./db/backup:/backup
      - ./db/data:/var/lib/mysql
    tty: true

  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./api
      dockerfile: ./api.Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/api.env

  myadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1